[main]
font = monospace:size=8
prompt = "$ "
# hide-prompt = true
letter-spacing = 0.5
icons-enabled = no
width = 24
horizontal-pad = 2
auto-select = true
enable-mouse = false
vertical-pad = 10
lines = 5
anchor = top

[colors]
background = "#000000ff"
text = "#e7e7e7ff"
prompt = "#abababff"
input = "#e7e7e7ff"
match = "#990000ff"
selection = "#101010ff"
selection-text = "#ffffffff"
selection-match = "#00ff00ff"
border = "#ffffffff"

[border]
width = 1
radius = 0
