colorscheme trm0
add-highlighter global/ number-lines
set global indentwidth 0

define-command wl-yank %{
	nop %sh{
		echo "$kak_selection" | wl-copy -n > /dev/null 2>&1
		fyi \
			--app-name="kakoune" \
			--icon="edit-copy" \
			--category="transfer.clipboard" \
			--transient \
			--hint=string:x-canonical-private-synchronous:clipboard \
			"copied" "$kak_selection"
	}
}

map global user y -docstring 'wl-copy' ':wl-yank<ret>'
map global normal w 'bf'
map global insert <c-a> <home>
map global insert <c-b> <left>
map global insert <c-f> <right>
map global insert <c-e> <end>
map global insert <c-d> <del>
map global insert <c-/> '<esc>lu'
map global insert <c-k> '<esc>Gidu'
map global insert <c-u> '<esc>Gudu'
map global insert <c-w> '<esc>bdu'
