"attribute" = "my_turquoise1"
"comment" = { fg = "my_gray5" }
"constant.character.escape" = "my_turquoise1"
"constant" = "my_white3"
"constant.numeric" = "my_turquoise1"
"constructor" = "my_yellow1"
"debug" = "my_yellow2"
"diagnostic.error" = { underline = { style = "curl", color = "my_red" } }
"diagnostic.hint" = { underline = { style = "line", color = "my_gray5" }, bg = "my_black"}
"diagnostic.info" = { underline = { style = "line" } }
"diagnostic" = { underline = { style = "line", color = "my_gray5" }, bg = "my_black"}
"diagnostic.warning" = { underline = { style = "curl", color = "my_yellow2" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }
"diff.delta" = "my_gray5"
"diff.minus" = "my_red"
"diff.plus" = "my_green"
"error" = "my_red"
"function" = "my_yellow1"
"hint" = "my_gray6"
"info" = "my_yellow2"
"keyword" = "my_red"
"label" = "my_red"
"markup.bold" = { modifiers = ["bold"] }
"markup.heading" = "my_yellow1"
"markup.italic" = { modifiers = ["italic"] }
"markup.link.text" = "my_white2"
"markup.link.url" = "my_turquoise2"
"markup.list" = "my_white2"
"markup.quote" = "my_brown"
"markup.raw" = "my_green"
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"namespace" = "my_white3"
"operator" = "my_white1"
"special" = "my_yellow1"
"string"  = "my_green"
"type" = { fg = "my_white3", modifiers = ["italic"] }
"ui.background" = { bg = "my_black" }
"ui.cursor" = { bg = "my_white4", fg = "my_black" }
"ui.cursorline" = { bg = "my_gray3" }
"ui.cursorline.primary" = { bg = "my_black" }
"ui.cursorline.secondary" = { bg = "my_black" }
"ui.cursor.match" = { fg = "my_white1", modifiers = ["bold"], underline = { style = "double_line", color = "my_white1" }, bg = "my_black"}
"ui.cursor.primary" = { fg = "my_white1", modifiers = ["reversed"] }
"ui.debug" = { fg = "my_yellow1", bg = "my_gray0" }
"ui.gutter" = { bg = "my_black" }
"ui.help" = { fg = "my_gray7", bg = "my_gray2" }
"ui.highlight.frameline" = { bg = "#8b6904" }
"ui.linenr" = { fg = "my_gray3", bg = "my_black" }
"ui.linenr.selected" = { fg = "my_gray7", bg = "my_gray"}
"ui.menu" = { fg = "my_white1", bg = "my_gray2" }
"ui.menu.selected" = { fg = "my_gray2", bg = "my_gray6" }
"ui.popup" = { bg = "my_gray2" }
"ui.selection" = { bg = "my_gray4" }
"ui.statusline" = { fg = "my_gray7", bg = "my_gray2" }
"ui.statusline.inactive" = { fg = 'my_gray5', bg = 'my_gray2' }
"ui.statusline.insert" = { fg = "my_black", bg = "my_gray6", modifiers = ["bold"] }
"ui.statusline.normal" = { fg = "my_gray7", bg = "my_gray2" }
"ui.statusline.select" = { fg = "my_gray7", bg = "my_black", modifiers = ["bold"] }
"ui.text.focus" = "my_white1"
"ui.text" = "my_white1"
# Invalid modifier: "normal". See 'https://github.com/helix-editor/helix/issues/5709'
"ui.virtual.inlay-hint" = { fg = "my_gray4", bg="my_black" } #, modifiers = ["normal"] }
"ui.virtual.inlay-hint.parameter" = { fg = "my_gray4", modifiers = ["normal"] }
#"ui.virtual.inlay-hint.parameter" = "my_gray4"
"ui.virtual.inlay-hint.type" = { fg = "my_gray4", modifiers = ["italic"] }
"ui.virtual.jump-label" = { fg = "my_yellow2", modifiers = ["bold"] }
"ui.virtual.ruler" = { bg = "my_gray3" }
"ui.virtual.whitespace" = { fg = "my_gray6" }
"ui.virtual.wrap" = "my_gray4"
"ui.window" = { fg = "my_gray3", bg = "my_gray0" }
"variable" = "my_white3"
"variable.other.member" = "my_brown"
"warning" = "my_yellow2"

[palette]
my_black      = "#101010"
my_brown      = "#ECD2E0"
my_gray0      = "#1B1B1B"
my_gray1      = "#252525"
my_gray2      = "#2F2F2F"
my_gray3      = "#3C3C3C"
my_gray4      = "#505050"
my_gray5      = "#636363"
my_gray6      = "#7A7A7A"
my_gray7      = "#B0B0B0"
my_gray8      = "#E7E7E7"
my_green      = "#CED1F8"
my_red        = "#FFA5D6"
my_turquoise1 = "#FFF0F1"
my_turquoise2 = "#CED1F8"
my_white1     = "#E7E7E7"
my_white2     = "#E7E7E7"
my_white3     = "#FFD6EE"
my_white4     = "#CED1F8"
my_yellow1    = "#A7A8DE"
my_yellow2    = "#CED1F8"
