# Globbing and other sht
bindkey -e

setopt extended_glob
setopt autocd               # Change to a directory just by typing its name
setopt auto_pushd           # Push directories onto the directory stack
setopt pushd_ignore_dups    # Do not add duplicate directories to the stack
setopt pushdminus           # Push directories onto the stack in the order they are visited

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=100000

unsetopt autocd beep notify

# Highlight
ZSH_SYNTAX_HIGHLIGHTNING_GUIX_STORE_PATH=$(guix build --no-grafts zsh-syntax-highlighting)
source $ZSH_SYNTAX_HIGHLIGHTNING_GUIX_STORE_PATH/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

case "$TERMINAL" in
    foot)
        source ~/.zshrc_foot
        ;;
    *)
        source ~/.zshrc_tty
        ;;
esac

# Aliases
alias fuck="lxsudo"

alias g='git'
alias gs='git status'

alias venv="source venv/bin/activate"

function c() {
  builtin cd "$@" && l
}

alias b='c ..'

generate_gitignore() {
  if [ -z "$1" ]; then
      echo "Please provide a list of technologies or languages, e.g., python,java"
      return 1
  fi
  curl -sL "https://www.toptal.com/developers/gitignore/api/$1" > .gitignore
  echo ".gitignore generated for: $1"
}

function mark() {
  export MARKED_DIR=$(pwd)
  echo "Marked"
}

function hook() {
  if [[ -n $MARKED_DIR ]]; then
    echo "Hooked $MARKED_DIR"
    c "$MARKED_DIR"
  else
    echo "No marks to hook."
  fi
}

