(define color-dark      #x101010)
(define color-base      #x1B1B1B)
(define color-bright    #x292929)
(define color-text      #xE7E7E7)
(define color-mute      #x464754)

(define color-yellow    #xFFF0F1)
(define color-pink      #xFFD6EE)
(define color-cyan      #xCED1F8)
(define color-dark-cyan #xA7A8DE)
(define color-red       #xFF95B6)
(define color-dark-pink #xF3E8E7)
