(define color-dark      #x101010)
(define color-base      #x1B1B1B)
(define color-bright    #x292929)
(define color-text      #xE7E7E7)
(define color-mute      #x636363)

(define color-yellow    #xFFF0F1)
(define color-cyan      #xA7A8DE)
(define color-pink      #xFFD6EE)
(define color-dark-cyan #xCED1F8)
(define color-red       #xFFA5D6)
(define color-dark-pink #xECD2E0)
